config/routes.rb
Tournament::Application.routes.draw do
  resources :teams
  resources :players
  get "main/index"
  resources :contests

  root 'main#index'

  

end

app/models/contest.rb
class Contest < ActiveRecord::Base
	
	has_many :players

  #attr_accessible :name, :started_on, :ended_on
  validates :name, presence: true, uniqueness: true
end

app/models/player.rb
class Player < ActiveRecord::Base

	belongs_to :contest
	belongs_to :team
	
	def name
		self.first_name + " " + self.last_name
	end
end

app/models/team.rb
class Team < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  def index
    @contests = Contest.all
  end

  def new
    @contest = Contest.new
  end

  def create
    @contest = Contest.new(post_params)
    if @contest.save
      redirect_to contests_url, :notice => "Successfully created contest."
    else
      render :action => 'new'
    end
  end

  def show
    @contest = Contest.find(params[:id])
    @players = @contest.players.order(:last_name)
  end
  
  private
  def post_params
    params.require(:contest).permit(:name, :started_on, :ended_on)
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
    @team = Team.new
  end

  def show
    @player = Player.find(params[:id])
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(post_params)
    if @player.save
      redirect_to @player, :notice => "Successfully created player."
    else
      render :action => 'new'
    end
  end

  def edit
    @player = Player.find(params[:id])
    @tournaments = Contest.all
  end

  def update
    @player = Player.find(params[:id])
    if @player.update_attributes(post_params)
      redirect_to @player, :notice  => "Successfully updated player."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    redirect_to players_url, :notice => "Successfully destroyed player."
  end

  private
  def post_params
    params.require(:player).permit(:first_name, :last_name, 
      :contest_id, :team_id)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(params[:team])
    if @team.save
      redirect_to teams_url, :notice => "Successfully created team."
    else
      render :action => 'new'
    end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])
    if @team.update_attributes(params[:team])
      redirect_to teams_url, :notice  => "Successfully updated team."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    redirect_to teams_url, :notice => "Successfully destroyed team."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/contests/index.html.erb
<%= render :partial => "main/header", locals: {page_title: "Tournaments"} %>

<div data-role="content">
  <div id="container">
    <%= render "main/flash" %>
    <div class="ui-grid-b">
        <div class="ui-block-a">Name</div>
        <div class="ui-block-b">Started On</div>
        <div class="ui-block-c">Ended On</div>
    </div>
    <div class="ui-grid-b">
      <% for contest in @contests %>
          <div class="ui-block-a"><%= link_to contest.name, contest_path(contest) %></div>
          <div class="ui-block-b"><%= contest.started_on %></div>
          <div class="ui-block-c"><%= contest.ended_on %></div>
      <% end %>
    </div>

    <div><%= link_to "New Tournament", new_contest_path, {"data-role" => "button", "data-icon" => "plus"} %></div>
  </div>
</div>    

app/views/contests/new.html.erb
<%= render :partial => "main/header", locals: {page_title: "New"} %>
<div data-role="content">
  <div id="container">
    <%= render "main/flash" %>

    <div><%= link_to "Back to List", contests_path, {"data-role" => "button", "data-icon" =>"grid", "data-inline"=>"true"} %></div>
    <%= form_for @contest do |f| %>
      <%= f.error_messages %>
      <div>
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>
      <div>
        <%= f.label :started_on %><br />
        <%= f.date_field :started_on %>
      </div>
      <div>
        <%= f.label :ended_on %><br />
        <%= f.date_field :ended_on %>
      </div>
      <div><%= f.submit "Submit" %></di>
    <% end %>

   
  </div>
</div>

app/views/contests/show.html.erb
<%= render :partial => "main/header", locals: {page_title: "Details"} %>

<div data-role="content">
  <div id="container">
		<div>
			<h2>Tournament: <%= @contest.name %></h2>
			<div>
				Players
				<ul>
					<% @players.each do |player| %>
						<li><%= player.name %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div data-role="page">
      <%= yield %>
      <div data-role="footer">
        <h4>Made By Anakhsoft</h4>
      </div>
    </div>
    
  </body>
</html>

app/views/main/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%= content_tag :h1, yield(:title) if show_title? %>

app/views/main/_header.html.erb
<div data-role="header">
  <%= link_to "Home", main_index_path, {"data-icon" =>"home"} %>
  <% if defined?(page_title) %>
  	<h1><%= page_title %></h1>
  <% end %>
</div>

app/views/main/index.html.erb
<%= render :partial => "header", locals: {page_title: "Main Menu"} %>
<div data-role="content">
  <div id="container">
		<ul data-role="listview">
			<li><%= link_to "Tournaments", contests_path() %></li>
			<li><%= link_to "Players", players_path() %></li>
			<li><%= link_to "Teams", teams_path() %></li>
			<li><%= link_to "Matches", "#" %></li>
		</ul>	
	</div>
</div>

app/views/players/_form.html.erb
<%= form_for @player do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>

  <p>
    Select Tournament
    <%= f.select "contest_id", options_from_collection_for_select(@tournaments, "id", "name") %>
      
  </p>  
  <p><%= f.submit %></p>
<% end %>

app/views/players/edit.html.erb
<%= render :partial => "main/header", locals: {page_title: "Edit Player"} %>
<div data-role="content">
	<% title "Edit Player" %>

	<%= render 'form' %>

	<p>
	  <%= link_to "Show", @player %> |
	  <%= link_to "View All", players_path %>
	</p>
</div>

app/views/players/index.html.erb
<%= render :partial => "main/header", locals: {page_title: "Players"} %>
<div data-role="content">

  <table>
    <% unless @players.blank? %>
      <tr>
        <th>Name</th>
      </tr>
    <% end %>
    <% for player in @players %>
      <tr>
        <%= form_for @team do |f| %>  
        <td><%= player.name %></td>
        <td><%= link_to "Show", player %></td>
        <td><%= link_to "Edit", edit_player_path(player) %></td>
        <td>
        <% end %>  
      </tr>
    <% end %>
  </table>

  <p><%= link_to "Add Player", new_player_path %></p>
</div>

app/views/players/new.html.erb
<%= render :partial => "main/header", locals: {page_title: "New Player"} %>
<div data-role="content">

	<%= render 'form' %>

	<p><%= link_to "Back to List", players_path %></p>
</div>

app/views/players/show.html.erb
<%= render :partial => "main/header", locals: {page_title: "Player"} %>
<div data-role="content">
	<% title "Player" %>

	<p>
	  <strong>Name:</strong>
	  <%= @player.name %>
	</p>

	<p>
	  <%= link_to "Edit", edit_player_path(@player) %> |
	 
	  <%= link_to "View All", players_path %>
	</p>
</div>